name = filterplus
author = monk
optional_depends = ranks, factions, exp2
description = Filter content and censor profanity from public chat stream. Includes API callback, moderation tools, and much more.
license = MIT
title = filterplus
forum = https://github.com/monk-afk/filterplus
