return {
    "rainbows",
    "puppies",
    "flowers",
    "Elon Musk",
    "kawaii",
    "kittens",
    "bunnie",
    "uwu",
    "cutee",
    "so pretty",
    "fantastic",
    "amazing",
    "the best",
    "woww",
    "kiki",
    "awww",
    "sunshine",
    "daisy",
    "lucky",
    "bubbles",
    "spooky",
    "monk",
    "unicorn",
    "jellybean",
    "Donald Trump",
    "Santa Clause",
    "lalalala",
    "what",
    "huh",
    "jumbo shrimp",
    "jimney crickets",
    "Pinocchio",
    "starlight",
    "Pochahontas",
    "barbie",
    "Garfield",
    "huuuu",
    "chartreuse",
    "om nom nom",
    "crunchwrap supreme",
    "pika pika",
    "meatball",
    "pew pew",
    "mama",
    "uncle Joe",
    "SquareOne",
    "chimken nuggets",
    "rice",
    "chia pets",
    "tamagochi",
    "furby",
}