  --==[[ FilterPlus 0.2.0 ]]==--
  --==[[ monk © 2023-2025 ]]==--
local accent_map = {
  ["Я"] = "r",
  ["я"] = "r",
  ["ю"] = "lo",
  ["Ь"] = "bl",
  ["ь"] = "bl",
  ["Ы"] = "bl",
  ["ы"] = "bl",
  ["Ъ"] = "bl",
  ["ъ"] = "bl",
  ["э"] = "e",
  ["Щ"] = "w",
  ["щ"] = "w",
  ["Ш"] = "w",
  ["ш"] = "w",
  ["Ч"] = "y",
  ["ч"] = "y",
  ["Ц"] = "u",
  ["ц"] = "u",
  ["Х"] = "x",
  ["х"] = "x",
  ["Ф"] = "o",
  ["ф"] = "o",
  ["У"] = "y",
  ["у"] = "y",
  ["Т"] = "t",
  ["т"] = "t",
  ["С"] = "c",
  ["с"] = "c",
  ["Р"] = "p",
  ["р"] = "p",
  ["П"] = "n",
  ["п"] = "n",
  ["О"] = "o",
  ["о"] = "o",
  ["Н"] = "h",
  ["н"] = "h",
  ["М"] = "m",
  ["м"] = "m",
  ["Л"] = "n",
  ["л"] = "n",
  ["К"] = "k",
  ["к"] = "k",
  ["Й"] = "n",
  ["й"] = "n",
  ["И"] = "n",
  ["и"] = "n",
  ["З"] = "e",
  ["з"] = "e",
  ["Ж"] = "x",
  ["ж"] = "x",
  ["ё"] = "e",
  ["Е"] = "e",
  ["е"] = "e",
  ["Д"] = "a",
  ["д"] = "a",
  ["Г"] = "r",
  ["г"] = "r",
  ["В"] = "b",
  ["в"] = "b",
  ["Б"] = "b",
  ["б"] = "b",
  ["А"] = "a",
  ["а"] = "a",
  ["μ"] = "u",
  ["α"] = "f",
  ["ŉ"] = "n",
  ["Þ"] = "p",
  ["þ"] = "p",
  ["Ż"] = "z",
  ["ż"] = "z",
  ["Ž"] = "z",
  ["ž"] = "z",
  ["Ź"] = "z",
  ["ź"] = "z",
  ["Ɏ"] = "y",
  ["ʏ"] = "y",
  ["Ÿ"] = "y",
  ["ÿ"] = "y",
  ["Ŷ"] = "y",
  ["ŷ"] = "y",
  ["Ý"] = "y",
  ["ý"] = "y",
  ["Ŵ"] = "w",
  ["ŵ"] = "w",
  ["Ʉ"] = "u",
  ["ᴜ"] = "u",
  ["Ū"] = "u",
  ["ū"] = "u",
  ["Ų"] = "u",
  ["ų"] = "u",
  ["Ũ"] = "u",
  ["ũ"] = "u",
  ["Ű"] = "u",
  ["ű"] = "u",
  ["Ü"] = "u",
  ["ü"] = "u",
  ["Ů"] = "u",
  ["ů"] = "u",
  ["Û"] = "u",
  ["û"] = "u",
  ["Ŭ"] = "u",
  ["ŭ"] = "u",
  ["Ù"] = "u",
  ["ù"] = "u",
  ["Ú"] = "u",
  ["ú"] = "u",
  ["Ŧ"] = "t",
  ["ŧ"] = "t",
  ["ᴛ"] = "t",
  ["Ţ"] = "t",
  ["ţ"] = "t",
  ["Ť"] = "t",
  ["ť"] = "t",
  ["ß"] = "s",
  ["ß"] = "b",
  ["Ş"] = "s",
  ["ş"] = "s",
  ["Š"] = "s",
  ["š"] = "s",
  ["Ŝ"] = "s",
  ["ŝ"] = "s",
  ["Ś"] = "s",
  ["ś"] = "s",
  ["s"] = "s",
  ["ſ"] = "i",
  ["Ɽ"] = "r",
  ["ʀ"] = "r",
  ["Ŗ"] = "r",
  ["ŗ"] = "r",
  ["Ř"] = "r",
  ["ř"] = "r",
  ["Ŕ"] = "r",
  ["ŕ"] = "r",
  ["ĸ"] = "k",
  ["ᴘ"] = "p",
  ["ᴏ"] = "o",
  ["Œ"] = "o",
  ["œ"] = "o",
  ["ǫ"] = "q",
  ["Ō"] = "o",
  ["ō"] = "o",
  ["Ø"] = "o",
  ["ø"] = "o",
  ["Õ"] = "o",
  ["õ"] = "o",
  ["Ő"] = "o",
  ["ő"] = "o",
  ["Ö"] = "o",
  ["ö"] = "o",
  ["Ô"] = "o",
  ["ô"] = "o",
  ["Ŏ"] = "o",
  ["ŏ"] = "o",
  ["Ò"] = "o",
  ["ò"] = "o",
  ["Ó"] = "o",
  ["ó"] = "o",
  ["Ŋ"] = "n",
  ["ŋ"] = "n",
  ["ɴ"] = "n",
  ["Ņ"] = "n",
  ["ņ"] = "n",
  ["Ñ"] = "n",
  ["ñ"] = "n",
  ["Ň"] = "n",
  ["ň"] = "n",
  ["Ń"] = "n",
  ["ń"] = "n",
  ["ᴍ"] = "m",
  ["ʟ"] = "l",
  ["Ŀ"] = "l",
  ["ŀ"] = "l",
  ["Ł"] = "l",
  ["ł"] = "l",
  ["Ļ"] = "l",
  ["ļ"] = "l",
  ["Ľ"] = "l",
  ["ľ"] = "l",
  ["Ĺ"] = "l",
  ["ĺ"] = "l",
  ["Ķ"] = "k",
  ["ķ"] = "k",
  ["ᴊ"] = "j",
  ["Ĵ"] = "j",
  ["ĵ"] = "j",
  ["ɪ"] = "i",
  ["ı"] = "i",
  ["Ĳ"] = "i",
  ["ĳ"] = "i",
  ["Ī"] = "i",
  ["ī"] = "i",
  ["Į"] = "i",
  ["į"] = "i",
  ["İ"] = "i",
  ["Ĩ"] = "i",
  ["ĩ"] = "i",
  ["Ï"] = "i",
  ["ï"] = "i",
  ["Î"] = "i",
  ["î"] = "i",
  ["Ĭ"] = "i",
  ["ĭ"] = "i",
  ["Ì"] = "i",
  ["ì"] = "i",
  ["Í"] = "i",
  ["í"] = "i",
  ["Ⱨ"] = "h",
  ["Ħ"] = "h",
  ["ħ"] = "h",
  ["Ĥ"] = "h",
  ["ĥ"] = "h",
  ["ɢ"] = "g",
  ["Ģ"] = "g",
  ["ģ"] = "g",
  ["Ġ"] = "g",
  ["ġ"] = "g",
  ["Ĝ"] = "g",
  ["ĝ"] = "g",
  ["Ğ"] = "g",
  ["ğ"] = "g",
  ["Ɇ"] = "e",
  ["ᴇ"] = "e",
  ["Ē"] = "e",
  ["ē"] = "e",
  ["Ę"] = "e",
  ["ę"] = "e",
  ["Ė"] = "e",
  ["ė"] = "e",
  ["Ë"] = "e",
  ["ë"] = "e",
  ["Ě"] = "e",
  ["ě"] = "e",
  ["Ê"] = "e",
  ["ê"] = "e",
  ["Ĕ"] = "e",
  ["ĕ"] = "e",
  ["È"] = "e",
  ["è"] = "e",
  ["É"] = "e",
  ["é"] = "e",
  ["ᴅ"] = "d",
  ["Ð"] = "e",
  ["ð"] = "e",
  ["Đ"] = "d",
  ["đ"] = "d",
  ["Ď"] = "d",
  ["ď"] = "d",
  ["ᴄ"] = "c",
  ["Ç"] = "c",
  ["ç"] = "c",
  ["Ċ"] = "c",
  ["ċ"] = "c",
  ["Č"] = "c",
  ["č"] = "c",
  ["Ĉ"] = "c",
  ["ĉ"] = "c",
  ["Ć"] = "c",
  ["ć"] = "c",
  ["ʙ"] = "b",
  ["ᴀ"] = "a",
  ["Æ"] = "a",
  ["æ"] = "a",
  ["Ā"] = "a",
  ["ā"] = "a",
  ["Ą"] = "a",
  ["ą"] = "a",
  ["Ã"] = "a",
  ["ã"] = "a",
  ["Ä"] = "a",
  ["ä"] = "a",
  ["Å"] = "a",
  ["å"] = "a",
  ["Â"] = "a",
  ["â"] = "a",
  ["Ă"] = "a",
  ["ă"] = "a",
  ["À"] = "a",
  ["à"] = "a",
  ["Á"] = "a",
  ["á"] = "a",
  ["ª"] = "a",
  ["₵"] = "c",
  ["₴"] = "s",
  ["₳"] = "a",
  ["₮"] = "t",
  ["₩"] = "w",
  ["₥"] = "m",
  ["₣"] = "f",
  ["£"] = "f",
  ["$"] = "s",
  ["@"] = "a",
  ["!"] = "i",
  ["’"] = "'",
  ["‘"] = "'",
  ["¡"] = "i",
  ["!"] = "i",
}

local number_map = {
  ["0"] = "o",
  ["1"] = "i",
  ["3"] = "e",
  ["4"] = "a",
  ["5"] = "s",
  ["6"] = "g",
  ["66"] = "gg",
  ["7"] = "t",
  ["8"] = "b",
}

local function sanitize(str)
  if str and str ~= "" then
    str = str--[[ :lower() ]]
      :gsub("[%z\1-\127\194-\244][\128-\191]*", function(c) return accent_map[c] or c end)
      :gsub("(%a+)[-,'`](%a+%f[%A])", "%1%2") -- merge words with apostrophes, i'll, you're, etc
      :gsub("(%a?)(%d+)(%a?)", function(pref, char, suff)     -- fix some l33t words
          return pref .. (number_map[tostring(char)] or char) .. suff
      end)
      :gsub("[^%a%s]+", " ")  -- replace remaining non-letter with a space
      :gsub("%s%s+", " "):gsub("^%s", ""):gsub("%s$","")  -- strip extra spaces
  end
  return str
end

return sanitize
------------------------------------------------------------------------------------
-- MIT License                                                                    --
--                                                                                --
-- Copyright © 2023-2025 monk (Discord ID: 699370563235479624)                    --
--                                                                                --
-- Permission is hereby granted, free of charge, to any person obtaining a copy   --
-- of this software and associated documentation files (the "Software"), to deal  --
-- in the Software without restriction, including without limitation the rights   --
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell      --
-- copies of the Software, and to permit persons to whom the Software is          --
-- furnished to do so, subject to the following conditions:                       --
--                                                                                --
-- The above copyright notice and this permission notice shall be included in all --
-- copies or substantial portions of the Software.                                --
--                                                                                --
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR     --
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,       --
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE    --
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER         --
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,  --
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  --
-- SOFTWARE.                                                                      --
------------------------------------------------------------------------------------
