-- List of exemptions created by the blacklist mutator
return {
  ["pura"] = true,
  ["nagger"] = true,
  ["deck"] = true,
  ["puti"] = true,
  ["shot"] = true,
  ["ship"] = true,
  ["fuul"] = true,
  ["ifu"] = true,
  ["sit"] = true,
  ["slit"] = true,
  ["spit"] = true,
  ["skit"] = true,
  ["pito"] = true,
  ["shut"] = true,
  ["put"] = true,
  ["puts"] = true,
  ["putt"] = true,
  ["seit"] = true,
  ["suit"] = true,
  ["semy"] = true,
  ["shim"] = true,
  ["sey"] = true,
  ["shiv"] = true,
  ["dice"] = true,
  ["shin"] = true,
  ["shift"] = true,
  ["soit"] = true,
  ["shirt"] = true,
  ["dock"] = true,
  ["duck"] = true,
  ["funk"] = true,
  ["shite"] = true,
}
